site_name: "Cayde"
theme:
  name: "material"
  
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - jensen
        - /home/project/asdf.py